export const GET_CITY_LIST_REQUESTED = 'GET_CITY_LIST_REQUESTED';
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS';
export const GET_CITY_DETAIL_REQUESTED = 'GET_CITY_DETAIL_REQUESTED';
export const GET_CITY_DETAIL_SUCCESS = 'GET_CITY_DETAIL_SUCCESS';
